% Copyright (C) 2017, Danas Sutula
%
% This file is part of the program XFEM_Fracture2D.
%
% XFEM_Fracture2D program is free software: you can redistribute it and/or 
% modify it under the terms of the GNU Lesser General Public License as 
% published by the Free Software Foundation, either version 3 of the 
% License, or (at your option) any later version.
%
% XFEM_Fracture2D is distributed in the hope that it will be useful, but 
% WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
% General Public License for more details.
%
% You should have received a copy of the GNU Lesser General Public License
% along with XFEM_Fracture2D. If not, see <https://www.gnu.org/licenses/>.


%==========================================================================
% RUN JOBS
%==========================================================================

% clear all
% close all

% % all jobs in library
% job_titles = { ...
% 'several_cracks/edge/vertical_tension', ...
% 'several_cracks/cross', ...
% 'several_cracks/inclusion',...
% 'growth_with_remeshing', ...
% 'random_cracks/10_cracks', ...
% 'random_cracks/100_cracks', ... % (takes about 10-15min)
% 'energy_minimisation/10_cracks', ... % (takes about 5min)
% 'compare_fracture_criteria/double_cantilever', ...
% 'compare_fracture_criteria/edge_cracks', ...
% 'movie-XFEM', ...
% 'movie-Thanks'
% };

% subset of jobs in library
job_titles = { ...
    'several_cracks/edge/vertical_tension', ...
... # 'several_cracks/cross', ...
... # 'several_cracks/inclusion', ...
...
... # 'growth_with_remeshing', ...
...
%     'random_cracks/10_cracks', ...
...
%     'compare_fracture_criteria/double_cantilever', ...
%     'compare_fracture_criteria/edge_cracks', ...
%     'compare_fracture_criteria/bouchard2003', ...
...
%     'several_cracks/bouchard2003/top_edge_pull', ...
%     'several_cracks/bouchard2003/vertical_extension', ...
%     'several_cracks/bouchard2003/vertical_tension',...
...
};

for job_title_i = 1:length(job_titles)
    job_title = job_titles{job_title_i};
    
    RUN_JOB
    
end

% exit(0)
