
%==========================================================================
% RUN JOBS
%==========================================================================

% clear all
% close all

% % Basic examples
job_titles = { ...
    'single_crack', ...
    'several_cracks/edge/vertical_tension', ...
    'several_cracks/cross', ...
    'several_cracks/inclusion', ...
    'growth_with_remeshing', ...
    'random_cracks/10_cracks', ...
};

% % Energy minimization examples
% job_titles = { ...
%     'energy_minimisation/10_cracks', ... % (takes about 5min)
%     'compare_fracture_criteria/double_cantilever', ...
%     'compare_fracture_criteria/edge_cracks', ...
%     'compare_fracture_criteria/bouchard2003', ...
% };

% % Movies
% job_titles = { ...
%     'movie-XFEM', ...
%     'movie-Thanks', ...
% };

for job_title_i = 1:length(job_titles)
    job_title = job_titles{job_title_i};
    
    RUN_JOB
    
end

% exit(0)
